### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by slavingia**
1. GitHub changes mean the image doesn't load sometimes.
2. Now that we have a visual website, we can keep the README cleaner.

### CODE REVIEW

**Comment by JoshSmith** [comment]
Can we implement code reviews here soon? I definitely missed this because `in progress` on all the @code-corps repos means "still a WIP", so didn't think it was ready for review yet.

**Comment by slavingia** [comment]
there's no process listed in the readme. i think it's worth adding the contributing stuff in code-corps. i'll follow your lead on that, as you know better than me (i gave it a shot, but there was enough repo-specific stuff in there i gave up on modifying everything to fit)

**Comment by slavingia** [comment]
what label should i have placed to make that it was waiting a review? i assumed all open PRs are pending review, but that's just how i normally work

**Comment by JoshSmith** [comment]
I think applying branch protection that reviews are required to merge is a good bet. Then you get benefit of "Review Required" and "Approved" labels for free.

**Comment by slavingia** [comment]
that would be a great start! can you turn that on? i don't think i have
that ability.

**Pull request merged**
