### PR TITLE
First attempt at Ohio transformer file

### PR DESCRIPTION
**Pull request by pjsier**
Taking a first stab a #71 with the Ohio voter file and tried it out on Sandusky County. 

Not sure about the best way of updating the type restrictions from `BaseTransformer`, but there were a few required items not included so I just made a copy and overwrote those columns. It might be worth considering making all columns allow `None`. 

Also, the original `OhioPrepare.py` file defaults mailing address information to the residential address information if none is provided, do we want to do that here as well?

### CODE REVIEW

**Comment by BenGalewsky** [comment]
Thanks Pat -- 

We are thinking about migrating the mailing address dim to be just Addr1, Addr2, City, State, Zip

But yes, if no mailing address is provided then we should fall back to the household

**Comment by BenGalewsky** [comment]
See issue #73 to see what I mean

**Comment by pjsier** [comment]
Changing the mailing address makes sense, especially because from a first look at Colorado's voter file there's definitely some weirdness there. For now I just updated it to fallback to the current mailing address format.

**Comment by BenGalewsky** [comment]
Merged into datamodel1.1 for further enhancement.

**Pull request closed without merging**
