### PR TITLE
Newbie Onboarding Branch

### PR DESCRIPTION
**Pull request by IohannesArnold**
At tonight's Hack Night, one of the things that came up was that it's difficult to onboard new would-be contributors because the repo is currently a wild collection of scripts and there is one centralized database that's difficult to replicate locally (and hence difficult to play around with).

My reaction to this is to create this branch, newbie-onboarding, which will be reorganized to be full of thorough documentation that will guide new contributors through the process of setting up a local edition of the database.

I am submitting this pull request to let you know about what I'm doing on my end, and offering perhaps that the main national voter file repo pull my newbie-onboarding branch into its own newbie-onboarding branch, in case any of the present developers would like to help me out. I am not actually proposing that you merge my newbie branch into this master. I'm still learning Github, so I don't know if what I'm technically doing is what I intend.

### CODE REVIEW

**Comment by JoshSmith** [comment]
I'm not sure this is quite what you want to do in terms of the branching strategy. Instead, it would make sense to open a series of issues and bite off tiny PRs to improve the onboarding. I can show you some of the lifecycle of how we did this in Code Corps if you want to come 👋 hello in [our Slack](http://slack.codecorps.org).

**Comment by BenGalewsky** [comment]
Thank you @IohannesArnold! 

I like the idea of the newbie on-boarding, but I agree with @JoshSmith about the complexity of a branch compared to just doing the work right here in master. Let's think about what would be the expectations of this newbie work?

Do you think the dockerfile is simple enough to get people going with their own DB?

I was thinking that a decent next step would be to run the scripts and load my generated Washington State test data into the db.

We could produce a similar file for Ohio so people could work on cleaning up these processes as needed and test them out in the docker env.

I really appreciate you joining into the conversation! We could move this to the google group to get wider feedback.

**Comment by IohannesArnold** [comment]
Thanks for the warm welcome! Personally, I'm still too new to this project in particular and to programming in general to feel comfortable proposing edits to the master branch directly. Having a separate branch would let me be more active since I would have the freedom to make mistakes. So unless you strenuously object, I'm going to keep my work in a separate branch in my own repo, at least for the time being. However, if you like what you see and would like to pull it into the master branch here, that's fine. I agree that it would be better to have a newbie-accessible master branch, it's just to get there I'd rather work in a separate branch.

**Comment by JoshSmith** [comment]
@IohannesArnold I definitely understand the anxiety there, but doing things in small pull requests with tiny commits in very focused branches is exactly how the process is supposed to work, regardless of ability level. We'd be _ecstatic_ to work with you to make a change be something you feel comfortable with. And rest assured, we merge things when we feel they're sound. You won't be committing directly to `master` and we always have right of refusal on anything! But I would really encourage you to submit pull requests even when you fear rejection, because it's ultimately a process that will help you learn and grow.

Would very much recommend coming into the Code Corps Slack where I'm sure others who have worn your shoes exactly will heartily agree with this sentiment.

**Pull request merged**
